import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>UNIP-E</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Estágio supervisionado - ATESTADO DE ESTÁGIO</h1>
      </main>

      <footer>
        <p>Denis Medeiros</p>
      </footer>
    </div>
  );
}
